name: Ruff check & format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff-check-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Specify the Python version you're using

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff check (lint)
        run: ruff check src/SKalsa_bot.py --verbose

      - name: Run Ruff format
        run: ruff format src/SKalsa_bot.py --verbose
